### ISSUE TITLE
add snapshot of training process to output directory

### ISSUE THREAD

**Issue by bjuergens** [neuroevolution-ai/NeuroEvolution-CTRNN_new#14]
(maybe only optional, as it would require a lot of hdd space to store a large population with lots of free parameters)

also make sure, that not the entire population is stored. For CMA no population needs to be stored. For mulambda only the parents need to be stored.

**Comment by pdeubel** [comment]
Do you mean for example storing every fifth or so generation during the training? And after training discarding, or keeping the intermediate results?

**Comment by bjuergens** [comment]
No, only keep the final population at the end of the training. 

There already is a snap-shot function, that stores everything needed to continue from that point on. 

For the implementation: only need to call that function once more at the end, using the output-dir as target. 

I think this would be a useful feature when doing larger experiments. I think it would be harmfull when doing hyperparameter search. So there should be a config parameter for this

**Comment by bjuergens** [comment]
ja

eher als CLI parameter. Allgemein: json für alles was auf's training einfluss hat. In CLI sachen für das programm an sich

default auf false (weil vllt unerwartet große dateien)

**Comment by bjuergens** [comment]
closing because it's implemented (in #38 i think)
