### ISSUE TITLE
handle larger populations across many workers

### ISSUE THREAD

**Issue by bjuergens** [neuroevolution-ai/NeuroEvolution-CTRNN_new#18]
this is not a big issue when running on few cores (8 or loss) but it becomes an issue when more cores (>20) are involved. 

When handling large populations (>10.000 individuals) then the worker are idle around 50% of the time, because the optimizer on the main thread is busy mutating the individuals and distributing them across the workers. 

todo

- [ ] look more closely at the issue and confirm my observation
- [ ] investigate wether this issue can be solve with dask-dataframes. 

When the genome is a dask-dataframe, than the mutation can happen on the worker-side. iirc dask can automatically send dataframes to the workers that need to process them. When the main thread only coordinates the dataframes (aka genomes) instead of actually reading and modifying them, then I believe we can speed up the system a lot.

**Comment by pdeubel** [comment]
In [Salimans17](https://arxiv.org/abs/1703.03864) they mutated the individuals in the workers by initializing a large noise array in each worker with the same seed for everyone. When mutating each worker choose an index in the worker and sent that back to the master from which the master could recreate the mutation. This is more efficient because only a scalar has to be transferred instead of the whole array.

**Comment by bjuergens** [comment]
this also comes with issues of its own. 

* CMA-ES can not work with this (or at least I can't see how)  (this is also an issue with my suggestion) 
* mu+lambda ES becomes harder to implement, and because of crossover both parents' random seeds need to be stored --> exponentially higher storage requirements. I haven't tested mu lambda ES without crossovers: maybe crossover don't even grant any kind of benefit. 
* significant implementation overhead (this is also an issue with my suggestion)

**Comment by bjuergens** [comment]
konkret habe ich mir das etwa so vorgestellt

Man betrachte den pseudocode von mulamda ES: 

<img src="https://user-images.githubusercontent.com/4362465/99153124-c535dc00-26a6-11eb-88d3-36f60ad1c23a.png" width="250">

Das ist die main-loop, die auf dem master ausgeführt wird. Die beiden funktionen "mutate" und "evaluate" (blau hervorgehoben) werden auf den worker ausgelagert. Im Vorfeld wird die population nicht als ein 2D numpy array angelegt, sondern als ein 2D [dask.array](https://docs.dask.org/en/latest/array.html) (was intern ein numby array ist). Wenn "mutate" aufgerufen wird, dann werden die IDs der beiden parents übergeben sowie die ID in der das Kind gespeichert werden soll. Wenn "evaluate" aufgerufen wird, dann wird die ID des individuums übergeben, dass evaluiert werden soll und der Worker schreibt die score des individuums in einer extra spalte des dask-arrays. für die "select" method wird einfach [topk](https://docs.dask.org/en/latest/array-api.html?highlight=topk#dask.array.topk) aufgerufen, um die besten mu individuuen auszuwählen. 


Das Schöne daran: Das Dask-Array wird verteilt auf den Workern gespeichert. Der Main Process bekommt die einzelnen Genome gar nicht zu gesicht (es sei denn vllt. bei der initialisierung) und der einzelne worker kennt auch nur sehr wenige genome (das, was er gerade bearbeitet und dann vllt. noch ein paar, die er für den Dataframe abspeichert). 

Ich denke mit diesem System kann man die gleiche effizienz erreich wie Salimans17, ohne dass man deren nachteile annehmen braucht. (Insb. tatsache, dass deren system nur dann gut funktioniert, wenn die anzahl der generationen sehr klein ist, und wenn die einzelnen genome sehr sehr groß sind)
___

Jetzt wo ich mehr darüber nachdenke. Ich denke man kann das auch mit einem redis server implementieren. Wobei ich denke, dass die Implementierung mit Dask einfacher ist, weil man einfach den dask.array wie ein np.array verwenden kann

**Comment by bjuergens** [comment]
daniel hatte gerade eine gute Idee: Da das bottleneck (vermutlich?) nur die mutation der genome ist, kann man einfach nur für diese eine stelle eine multithreading geschichte implementieren. Dadurch würden wir jetzt schon einen signifikanten speedup bekommen (~50%) und wir könnten jetzt schon auf größere genome gehen. Dann hätten wir zwar nicht das unbegrenzte Scaling wie in dieser Issue vorgeschlagen, aber man würde trotzdem schon relative weit kommen

**Comment by bjuergens** [comment]
I think the cleanest solution for this would be to re-implement DEAP with numpyarrays (are at least the parts, that deal with the genome directly)

**Comment by bjuergens** [comment]
closed because inactivity.

feel free to reopen, if we want to address this topic again in the future (even if it's just for discussion)
