### ISSUE TITLE
configuration reading

### ISSUE THREAD

**Issue by bjuergens** [neuroevolution-ai/NeuroEvolution-CTRNN_new#20]
currently the reading of the configurations is very ugly. Everything happens in [a helper functions with lots exeptions for different cases](https://github.com/neuroevolution-ai/NeuroEvolution-CTRNN_new/blob/f65d3cf63f64ef32f9bb3499462d24dbca937a09/neuro_evolution_ctrnn/tools/helper.py#L68). 

Better would be something, where each configuration class is mapped to a type-string. And when the type string is encountered in the config-dict, then the corresponding class is used. The mapping between class and string can be done with a simple global dict. When a new values needs to be added to the dict, this should happen at the same location where new configuration class is defined. 

This change would satisfy Open–closed principle and thus it will become much simpler to add new configuration classes.

**Comment by bjuergens** [comment]
related: #19

**Comment by pdeubel** [comment]
I encountered a bug regarding a false configuration which is not covered by our test case. In the `step()` function of the `BehaviorWrapper` there is a check for configuration values:

https://github.com/neuroevolution-ai/NeuroEvolution-CTRNN_new/blob/f65d3cf63f64ef32f9bb3499462d24dbca937a09/neuro_evolution_ctrnn/tools/env_handler.py#L195-L212

Without running the experiment this error is not discovered. This could be fixed when the configuration parsing is refactored or we could simply extend the test case to run the experiment for one generation or something like that.

**Comment by bjuergens** [comment]
I think that specific error is fine. The configuration-handling should catch general errors, but when some specific errors emerge elsewhere in the code, that's fine, too. Also this specific exception is not a bug. I think if there is a bug here, it's the exception-message, which could be  misleading in some cases.  

That being said: I think we could still improve that particular method. The first that comes to mind are actual unit tests for that class (using mock-envs and such). 

Also after this issue has been implemented, the if-elif block could be replaced with polymorphism ([explanation](https://refactoring.guru/replace-conditional-with-polymorphism)). The polymorphism could make sure, that the error is thrown when initiating the class, which would happen before the step method is called. But in this particular case I think this solution would add too much complexity for too little benefit. 

I don't think there is a way to avoid this exception in the step method without violating DRY and without adding an unreasonable amount of complexity.

**Comment by bjuergens** [comment]
relevantes bit an information: 

https://realpython.com/primer-on-python-decorators/#registering-plugins

**Comment by bjuergens** [comment]
was implemented in #41 (i think)
