### ISSUE TITLE
default values for configurations

### ISSUE THREAD

**Issue by bjuergens** [neuroevolution-ai/NeuroEvolution-CTRNN_new#21]
As the we learn about the influence of hyper parameters on the project, we tend to use more and more default values for each of them. Also as the system grows, the number of parameters also grows. 

Currently each configuration file must explicitly contain each parameter used in the experiment. The benefit of this is, that the user is always aware of which parameters exists. The downside is, that they must decide for values for parameters they don't know anything about. 

The current system allows for setting default paramters simply be adding the value after the member of the respective function. For example: adding a default value of "10" to "mu" for CMAES would simply look like this: 

```python3
@attr.s(slots=True, auto_attribs=True, frozen=True)
class OptimizerCmaEsCfg(IOptimizerCfg):
    population_size: int
    sigma: float
    mu: int = 10
```

When deciding which parameters get default values, the following questions need to be answered: 

* Do we even need this parameter? If we always use the same default value, why shouldn't we get rid of the paramter?
* When the parameter is omitted, will the system behave as the user expects it to behave? 
* How will the user know about the existence of the parameter in case they want to change it?

To address the last question, I think it would be good, if the actual configuration would be printed to stdout at the beginning of each experiment. 

related: #19 #20

**Comment by bjuergens** [comment]
For the record: Ich habe keine Lust darauf, dass wir default parameter einführen, und ich dann alle 2 Wochen gefragt werde, ob es einen Parameter gibt mit dem man XYZ einstellen kann. Ich habe außerdem keine Lust darauf, dass einige Parameter doppelt und dreifach implementiert werden, weil der der es implementiert hat nicht wusste, dass der parameter bereits existiert.

**Comment by bjuergens** [comment]
Außerdem: ich denke es wäre sinnvoll, wenn wir anfangen hinter jeden parameter einen kommentar schreiben, der erkärt wofür dieser paramter gebraucht wird. Das würde dann etwa so aussehen wie die Syntax von [tap](https://github.com/swansonk14/typed-argument-parser).

**Comment by bjuergens** [comment]
implementation is blocked until consensus is reached on the discussion

**Comment by bjuergens** [comment]
ergebnis / todo: 

ja

configuration.py in readme referenzieren

da wo default offensichtlich ist den default parameter setzen

hier in die isssue explizit reinschreiben welche defaults verwendet werden. und wenn jeder es gelesen hat, dann issue schließen

**Comment by bjuergens** [comment]
ich habe jetzt ein paar default values gesetzt: https://github.com/neuroevolution-ai/NeuroEvolution-CTRNN_new/commit/be123a7959e8728bf566dcf492be980252d7bd3c?branch=be123a7959e8728bf566dcf492be980252d7bd3c&diff=unified#diff-7c93efa8dd93eeae3dc380d3e6886b04a3bd977a88508728f2037d846c7a7218

wenn ihr beide grünes licht gibt, dann schließe ich die issue.

**Comment by bjuergens** [comment]
das `kw_only=True` braucht atttr um gleichzeitig vererbung und default-parameter zu verwenden https://github.com/python-attrs/attrs/issues/38#issuecomment-429033526

**Comment by pdeubel** [comment]
Passt für mich :+1:
