### ISSUE TITLE
mehrere ctrnn state updates pro step

### ISSUE THREAD

**Issue by bjuergens** [neuroevolution-ai/NeuroEvolution-CTRNN_new#26]
implementation:

- [x] neuer hyperparameter "substeps"
- [x] for i in range(conf.substeps): update state

vorteil: 

* netz können schneller reagieren
* continuirlichkeit der netze wird besser genutzt
* keine zusätzlichen freien parameter. 
* optimierung wird nicht komplexer

mögliche Nachteile:

* zustand fluktuiert vielleicht stärker
* vielleicht schlechteres gedächtnis

**Comment by DanielZim** [comment]
Gute Idee. Es gibt hier aber noch den Nachteil, dass sich dadurch die Rechenzeit verlängert.

**Comment by bjuergens** [comment]
weiterer vorteil: wir können frameskips in der env einbauen, um rechenzeit zu sparen. (z.B. atari braucht für einen einzelnen frame etwa genau so so lange als wenn man 4 frames in einen rutsch ausführt). Wenn man viele frameskips macht (z.B. 4 oder 8 oder 16), dann wird die step funktion vom brain entsprechend seltener aufgerufen. Dadurch hat das brain weniger schritte, um nachzudenken, und der Zeitdruck wird höher. Durch dieses Issue, wird der zeitdruck wieder verringert, und das brain kann mit höheren frameskips klarkommen, sodass wie sehr viel rechenzeit sparen können.

Es stellt sich die frage, wieviele rechenzeit durch die verschiedenen frameskips gespart werden kann. (insb. bei procgen)
