### ISSUE TITLE
refactor brain class initialization

### ISSUE THREAD

**Issue by bjuergens** [neuroevolution-ai/NeuroEvolution-CTRNN_new#54]
[this block](https://github.com/neuroevolution-ai/NeuroEvolution-CTRNN_new/blob/50eed32d63098a6724a8436f77d42f2e5658378e/neuro_evolution_ctrnn/tools/experiment.py#L43) is very ugly. 

I think it can be refactored similarly how we refactored the initialisation of the config-objects in #20. 

See this commit for basic idea: https://github.com/neuroevolution-ai/NeuroEvolution-CTRNN_new/pull/41/commits/aefe2c201754a9e33a5c251e65171077471f6f12

See this PR for final version: https://github.com/neuroevolution-ai/NeuroEvolution-CTRNN_new/pull/41/files

**Comment by bjuergens** [comment]
for this it will be much much simpler than for the configs, because no recursion is needed. 

todo: 

- [ ] added register magic to brain classes, which creates a singleton-dict named `registered_brain_types` 
- [ ]replce of the ugly block with `self.brain_class = registered_brain_types[self.config.brain.type]`

**Comment by pdeubel** [comment]
This can be closed as its solved with #55 right?
