### ISSUE TITLE
Prepare Feed-Forward NN (ffnn) class to implement Hyperbrain

### ISSUE THREAD

**Issue by DanielZim** [neuroevolution-ai/NeuroEvolution-CTRNN_new#63]
The following things should be implemented in the ffnn class to use it as a compositional pattern producing network (cppn) for the indirect ctrnn encoding (aka hyperbrain):

- [x] Investigate and tune the speed of the step/predict method, since this is a major bottleneck for hyperbrain (very important)
- [x] Add a linear activation function to the output layer to get an output value range [-inf; +inf] of the ffnn (in order to encode weights)
- [x] Refactor/tidy up the ffnn class a little bit

**Comment by bjuergens** [comment]
implentation in #65
