### ISSUE TITLE
uniform floating point precision

### ISSUE THREAD

**Issue by bjuergens** [neuroevolution-ai/NeuroEvolution-CTRNN_new#9]
Background: Salimans et al (2017) suggest that reduced floating point precision increases processing speed and at the same time it doesn't significantly reduce performance of the neural network. This has motivated me to reduce floating point precision in this project. But I was sloppy and didn't do this every where. 

Problem: This mismatch between floating point precision may force unneded conversion and thus slow down processing time instead of increasing it. 

Solution: first evaluate the impact of possible floating point conversions. then either convert as much as possible to float16 or convert as much as possible to float32. 

Note: some libraries require certain precision. iirc torch requires float32 for input vectors when using cnn.

**Comment by bjuergens** [comment]
untersuchen ob python jemals in kontakt zu den werten tritt, die in den gewichten/genomen tritt. Theorethisch sollten das alles numpy arrays sein, die niemals von python direkt bearbeitet werden

**Comment by pdeubel** [comment]
> untersuchen ob python jemals in kontakt zu den werten tritt, die in den gewichten/genomen tritt. Theorethisch sollten das alles numpy arrays sein, die niemals von python direkt bearbeitet werden

Ich bin beim Untersuchen von was anderem darauf gestoßen dass DEAP, zumindest bei CMA-ES bei Mu+Lambda hab ichs noch nicht untersucht, für die internen Werte/Arrays sowie die Population `float64` benutzt. Daher haben wir bei jedem Aufruf von `EpisodeRunner.eval_fitness()` ein float64 Individuum.

Ich hab noch keine Möglichkeit gesehen den Datentyp für DEAP bzw. im Konkreten für die CMA-ES Strategie zu ändern.

**Comment by bjuergens** [comment]
das ist doof. 

alles was mir spontan einfällt um da float16 zu erzwingen ist ziemlich hacky. 

Am saubersten wäre wohl alles zu float16 zu konvertieren, was aus DEAP rauskommt, aber ich würde vermuten, dass dann nicht mehr viel von dem speed up übrig bleiben wird. 

Sauber wäre vllt. wenn man einen DEAP fork macht, wo wir das einfach selbst fixen, aber ich vermute dass das den Aufwand nicht wert ist.

**Comment by bjuergens** [comment]
https://github.com/neuroevolution-ai/NeuroEvolution-CTRNN_new/pull/38/files/54c11d68d4601d11814cd0fc562983a38b046b3a#r545849839

**Comment by bjuergens** [comment]
closing because inactivity. Feel free to reopen, if we want to adress this subject again
